import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Black Cinema Daily</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Black Cinema Daily
        </h1>

        <h1 className="title">
            Read{' '}
          <Link href="/movies/movies">
            <a>Movies</a>
          </Link>
        </h1>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
